### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by jamesmills** [jamesmills/laravel-notification-rate-limit#1]
**Background**

I have an application which accepts a Conversion via a webhook URL. It's basically an API endpoint that accepts a ping when something happens.

When a Conversion is sent to the API via a webhook there is some code which checks to see if some of the values sent are valid. You can send a ConversionClickId and if this is invalid that it will fire an event. There are also notifications which are fired to notify the user who sent the webhook that it contains an invalid ClickId.

If the implementation was set up wrongly then the webhook could fire a load of times with an invalid ClickId which would cause loads of notifications to be sent to the user. I would like to throttle these or "rate limit" them somehow.

**Background research**

I have not found any packages out there and I am sure that this is something which a number of people need to do in their applications. I found this article with some good ideas https://scottwakefield.co.uk/journal/rate-limiting-notifications-in-laravel/

**Initial Q&A**

Q: The hard part is to decide what makes a notification unique. Do all data have to be equal? Or only specific keys?

A: It's purely the fact that the Notification has been fired. It does not matter about any of the data being passed. I suggest we just cache the UserId and the Notification class name as a key to check against.

Q: And will it check during queuing or when it's really send?

A: Probably somehow hooked into the Notification request lifecycle when it's about to be sent? I'm not sure. Not sure it matters. 

Q: Another question that comes to mind is how it handles multi channel notifications? Will the SMS be suppressed if email was first?

A: In the initial release (could lad other options on later) It would stop the entire Notification from processing any of the channels.

**Suggested solution and opinionated assumptions** 

- I like the idea of writing a Trait that can be added to a Notification class. 
- I like the idea of using the cache and using a hash of the User and Notification class name.
- I like the idea of using the Illuminate\Cache\RateLimiter 
- I like the idea of being able to override on the Notification class the `throttleKey` and `cachTimeout` if the user of the package wants to. A reasonable default would be set, maybe in the congif.
- It would stop all channel notifications being sent for that notification event

**Comment by Gummibeer** [comment]
I'm not this deep in notifications right now but you always handle an instance of a notification class!? So I would use a method for the `throttleKey` which should return the full identifier/key including all data that make the notification unique.
By default it could return `{user.id}.{notification.class}.{payload.serialized}`. This could be customized to the needs of the user.

Most times I like methods more than properties because they can contain logic, are enforceable via interface/abstract.

Using as much core as possible is a good idea! Would use the middleware as base idea.

If a notification is throttled it should fire an event to allow custom behavior with the notification. Like collect them for a later notification, write them into DB or do whatever the user wants.

**Comment by jamesmills** [comment]
@Gummibeer @edgrosvenor I would love to get your feedback on my initial WIP

I've struggled with this a little bit to be honest because it was not as "simple" as I thought it was going to be.

I've created a new `ThrottledNotifiable` class which needs to replace the default `Notifiable` trait on the `User` Model. This gives us access to the `notify()` function so we can add a throttle check here. This means the throttle is applied to the entire notification meaning it will stop any notification for all channels.

I've then created a `ShouldThrottle` interface and a `ThrottledNotification` trait. Both of these need to be added to any notification you would like to throttle. The nice thing about adding these is it allows us to apply some defaults and also allows us to check if the notification implements `ShouldThrottle` at run time so all other notifications won't be affected.

The package will fire a `NotificationRateLimitReached` event when the throttle is used.

I am leveraging Laravel’s RateLimiter class so as not to reinvent the wheel.

_Things to note_

1. I've added a default key which could do with an update
2. I've added the ability to add a `throttleForSeconds()` to the notification which will override the package default
3. I am firing an event called `NotificationRateLimitReached` but I'm not sure if this is the best way to do it. What if people need to update this and add a 'broadcastOn' for example?
4. I still need to tidy up the repo
5. I added basics to the README
6. The package has no tests.

**Comment by Gummibeer** [comment]
Regarding the event: you could use service binding or config value to override the default event by any event the user wants to get fired on throttle.

Regarding the `notify()` method - I'm not sure about it. Because it applies the throttle on call and not on notify so far I've got it?
So I can queue a notification every minute for a fixed timestamp and at this timestamp the user will get 100 notifications? 🤔

After first read I'm not 100% happy with the naming of `throttleForSeconds()`. In general I'm not 100% happy with `throttle`. 😕
For me throttle sounds more like delaying and not preventing/blocking. Throttle, for me, is like adding a 5sec timeout to each attempt. But the notification getting "throttled" is simply prevented/blocked/deleted - it will never get send again.

How about keeping the underlying logic name - `RateLimit`?

**Comment by jamesmills** [comment]
Like the idea of renaming to `laravel-notification-rate-limit`. You are right, it's not really a throttle, it will block and never send any notifications that are rate limited.

maybe rename `throttleForSeconds` to `rateLimitSeconds()` ?

>  So I can queue a notification every minute for a fixed timestamp and at this timestamp the user will get 100 notifications?

Unsure of the use case for this. For my initial needs, it works well. Given there is nothing else out there that even attempts to help with this issue I think this could be a good attempt. Maybe for an initial attempt at something this works well and additional functionality or checks could be added later.

**Comment by Gummibeer** [comment]
Payment notifications for example are very common to be queued to a fix date.
Combined with snooze you can queue a notification to pay the monthly fee and suppress it if it's already paid until then.
The rate limiter in this case would be to prevent multiple reminders because of different raceconditional logics.

Or even for a simpler case like a slow overloaded email queue.

So it's definitely a difference if it ratelimits right before sending or if the notification is dispatched.

**Comment by jamesmills** [comment]
OK, take two.

I have removed the need to replace the `Notifiable` in the User model.

I have now added an override in the packages service provider to override the `ChannelManager`. This does the same functionality as before but does it in the dispatcher instead.

This currently only overrides the `send()` function and not the `sendNow()`.

```
$this->app->singleton(ChannelManager::class, function ($app) {
    return new RateLimitDispatcher($app);
});
```

https://github.com/jamesmills/laravel-notification-throttle/commit/242711b278fdf5025c90df411d3f549329a92110

I have absolutely no idea if this will work with queued notifications or if this is the correct way to hook into the actual place of the application that sends the notifications. Hopefully someone can help guide me.

**Comment by edgrosvenor** [comment]
@jamesmills You are definitely on the right track I think. I agree that changing it from throttle to rate limit is more semantically correct. One thing I'd add to what you've done here is to let the user configure whether or not to log skipped notifications. I have one app where I know that from time to time there are going to be notifications skipped, I know why it's going to happen, and I really don't care about it enough to bother logging it. So I'd add a configuration option like `logSkippedNotifications` with a default value of true.

@Gummibeer With the payment example it seems like you're interacting more with the underlying event that would cause the notification and not the notification itself. Also, since this package uses the cache to store its data and determine whether or not a notification should be sent, it's probably not ideal for a long term snooze like that because if the cache is cleared after each deployment, for instance, the fact that the notification is suppressed would be lost.

As for your most recent comment, I think maybe some tests are called for. Let me see if my afternoon allows me to write some tests. I *think* what you have there would work with queued notifications but without code diving or writing a couple tests I can't be sure. I'm alone with a 4-year-old this week as my wife is locked in a cave running a remote town hall for work. So I'll be working in very short bursts and might be slow to respond.

**Comment by jamesmills** [comment]
@edgrosvenor regarding `logSkippedNotifications` https://github.com/jamesmills/laravel-notification-rate-limit/commit/423eab0cc0dbc0de6b20dd34c81a0e7490aedfff

**Comment by jamesmills** [comment]
Also updated all namespace and package name to `LaravelNotificationRateLimit` and `laravel-notification-rate-limit` etc.

**Comment by jamesmills** [comment]
Added `serialize` to the key which now consists of `{prefix}.{notification.class}.{payload.serialized}.{user.id}` (prefix is configurable in published config).

TODO: Not sure what happens if you try to send a notification to more than one user.

**Comment by jamesmills** [comment]
tagging v1 now!
