### ISSUE TITLE
Rate limiting is not applied to notifications dispatched with an associated 'delay'

### ISSUE THREAD

**Issue by grantholle** [jamesmills/laravel-notification-rate-limit#14]
I have a notification that I delay for a minute, but they are never throttled. I'm using redis as my queue driver. Whenever I remove the delay, they are throttled as expected.

**Comment by tibbsa** [comment]
*Diagnosis*: Currently we only override the `send` function from `ChannelManager`. When a delayed notification is sent, it passes through `send` but then is not ultimately delivered. When the queue worker delivers the actual notification, it calls `sendNow` to fire off the notification. 

*Simple answer*: The `send` rate checking logic must also be applied to `sendNow`. 

*Caveat*: If the length of the delay is less than the throttle rate, and we check for rate limiting in both `send` and `sendNow`, the notification will never get dispatched since the `send` check will set a timer that will not have expired before `sendNow` is hit. But `sendNow` may be used in other contexts as well. 

*Proposed solution*: Implement rate limiting for both `send` and `sendNow`, but skip it in `send` if there is a delay associated with the notification, so that rate limiting will be tested at the point of actually sending the notification rather than when it is queued up.
