### ISSUE TITLE
Cache Key on DynamoDb Error with big notification parameters

### ISSUE THREAD

**Issue by felipehertzer** [jamesmills/laravel-notification-rate-limit#39]
Hi @jamesmills,

I'm encountering an issue when the notification has parameters that exceed 2048 bytes. The error seems to be related to the use of `serialize($notification)` to build the cache key. 

**Error Message:**
```
Aws\DynamoDb\Exception\DynamoDbException: One or more parameter values were invalid: Size of hashkey has exceeded the maximum size limit of 2048 bytes
```

**Suggested Solution:**

To prevent this, would it be possible to use `md5` on the serialized object? This way, the cache key will remain unique while keeping the size within the limit.

Thanks for your help!

**Comment by tibbsa** [comment]
Changing the default cache keys would amount to a breaking change, since there is a possibility that someone out there is relying on the current behaviour to generate those keys. That is unlikely but we will only find that out the hard way of we break it.

If you have a large notification type that includes so much data that `serialize()` is generating such large cache keys, could you not resolve this by:

- disabling the automatic uniqueness check on that notification (i.e. adding `protected $shouldRateLimitUniqueNotifications = false;` to the notification class); and
- adding your own custom cache key part that includes the MD5 or SHA1 hash, i.e.

```
public function rateLimitCustomCacheKeyParts()
{
    return [
        md5(serialize($this))
    ];
}
```

Is there a reason this isn't all that manageable -- e.g. you have dozens of these notifications, and want to use uniqueness checks, but not re-implement all over the place? 

Perhaps the *best* option is to make this configurable.  Rather than change the current implementation, we would give users the global option to either use the `serialize()`'d string, _or_ to use a callback to generate a hash globally across all notifications (be that `md5()`, `sha1()`, or something else).

**Comment by felipehertzer** [comment]
Hello @tibbsa,

I believe the benefits of using md5 in combination with serialize outweigh the alternative. To ensure all notifications are sent reliably, we could leave a default setting that guarantees delivery while allowing customisation for cases where the serializer is needed on the cache key.

Also, the package does not validate or flag this issue. For instance, if a parameter, such as a array or a text, the notification may fail to send. The risk of an important notification not being delivered outweighs the minimal chance of someone expecting to see a cache key with serialize.

**Comment by tibbsa** [comment]
I do agree that in the event of some failure occurring in what this package is doing, as much as possible we should ensure that the underlying notification gets sent -- even if that is ignoring the rate limit.  In this case if a cache set can stop a request then we need to work around that. 

I will work on both aspects of this.

**Comment by tibbsa** [comment]
@felipehertzer I just tagged v3.1.0 which should allow you to resolve this globally.  Just add:

```
    'unique_notification_strategy' => 'md5',
```

... to your `config/laravel-notification-rate-limit.php` file.

**Comment by felipehertzer** [comment]
Hey @tibbsa, thanks it looks good.
